
import { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Plataforma de E-commerce Corporativo',
    year: 2023,
    tags: ['UI/UX', 'Web Dev'],
    imageUrl: 'https://picsum.photos/seed/project1/800/600',
    description: 'Redesign completo da interface de uma plataforma B2B, focado em usabilidade e performance.',
    longDescription: 'O projeto envolveu uma pesquisa aprofundada com usuários para identificar pontos de atrito na jornada de compra. A partir dos insights, criamos uma nova arquitetura de informação e um design system robusto. A interface foi reconstruída utilizando React e TypeScript, resultando em um aumento de 30% na conversão e 50% na velocidade de carregamento.',
    technologies: ['React', 'TypeScript', 'Figma', 'Node.js', 'PostgreSQL'],
    galleryImages: [
      'https://picsum.photos/seed/project1_gal1/1200/800',
      'https://picsum.photos/seed/project1_gal2/1200/800',
      'https://picsum.photos/seed/project1_gal3/1200/800',
    ],
  },
  {
    id: '2',
    title: 'Aplicativo de Fitness e Bem-estar',
    year: 2023,
    tags: ['Mobile', 'UI/UX'],
    imageUrl: 'https://picsum.photos/seed/project2/800/600',
    description: 'Criação de um aplicativo móvel para acompanhamento de treinos e hábitos saudáveis.',
    longDescription: 'Desenvolvemos um aplicativo nativo para iOS e Android com foco em uma experiência gamificada e social. A interface foi projetada para ser intuitiva e motivadora, com dashboards personalizáveis e integração com wearables. O backend foi construído em Firebase para garantir escalabilidade e sincronização em tempo real.',
    technologies: ['React Native', 'Firebase', 'Sketch', 'Lottie'],
    galleryImages: [
      'https://picsum.photos/seed/project2_gal1/800/1200',
      'https://picsum.photos/seed/project2_gal2/800/1200',
    ],
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: '3',
    title: 'Dashboard de Análise de Dados',
    year: 2022,
    tags: ['Web Dev', 'Data Viz'],
    imageUrl: 'https://picsum.photos/seed/project3/800/600',
    description: 'Ferramenta de visualização de dados para o setor financeiro, com gráficos interativos.',
    longDescription: 'Construímos uma aplicação web complexa que permite a analistas financeiros visualizar e interagir com grandes volumes de dados de mercado. Utilizando D3.js e React, criamos uma série de gráficos customizáveis e de alta performance. O design é clean e focado na clareza da informação.',
    technologies: ['React', 'D3.js', 'Python (API)', 'GraphQL'],
    galleryImages: [
      'https://picsum.photos/seed/project3_gal1/1200/800',
      'https://picsum.photos/seed/project3_gal2/1200/800',
    ],
  },
  {
    id: '4',
    title: 'Website Institucional para Agência Criativa',
    year: 2022,
    tags: ['Web Design', 'Branding'],
    imageUrl: 'https://picsum.photos/seed/project4/800/600',
    description: 'Desenvolvimento do novo portal de uma agência, com foco em branding e interatividade.',
    longDescription: 'O desafio foi traduzir a identidade visual arrojada da agência em uma experiência web imersiva. O site utiliza animações sutis (GSAP), transições de página suaves e um layout assimétrico para criar um impacto visual memorável. O gerenciamento de conteúdo é feito através de um CMS headless (Contentful).',
    technologies: ['Next.js', 'GSAP', 'Contentful', 'Tailwind CSS'],
    galleryImages: [
      'https://picsum.photos/seed/project4_gal1/1200/800',
      'https://picsum.photos/seed/project4_gal2/1200/800',
      'https://picsum.photos/seed/project4_gal3/1200/800',
    ],
  },
  {
    id: '5',
    title: 'Sistema de Gerenciamento Interno',
    year: 2021,
    tags: ['Web Dev', 'UX'],
    imageUrl: 'https://picsum.photos/seed/project5/800/600',
    description: 'Criação de uma ferramenta interna para otimização de processos e gestão de projetos.',
    longDescription: 'Desenvolvemos uma solução SaaS interna para uma empresa de logística, centralizando o controle de frotas, entregas e comunicação. A interface foi projetada para ser extremamente funcional e fácil de usar em ambientes de alta pressão. A aplicação é robusta, segura e otimizada para performance.',
    technologies: ['Vue.js', 'Laravel', 'Inertia.js', 'MySQL'],
    galleryImages: [
      'https://picsum.photos/seed/project5_gal1/1200/800',
    ],
  },
  {
    id: '6',
    title: 'Identidade Visual para Startup de IA',
    year: 2023,
    tags: ['Branding', 'Design System'],
    imageUrl: 'https://picsum.photos/seed/project6/800/600',
    description: 'Criação de uma identidade visual completa e um design system para uma startup de tecnologia.',
    longDescription: 'O projeto começou com a definição da estratégia de marca, resultando em um logo moderno e versátil. Em seguida, desenvolvemos um design system completo em Figma, incluindo paleta de cores, tipografia, componentes de UI e guias de uso, garantindo consistência em todos os produtos digitais da empresa.',
    technologies: ['Figma', 'Adobe Illustrator', 'Storybook'],
    galleryImages: [
      'https://picsum.photos/seed/project6_gal1/1200/800',
      'https://picsum.photos/seed/project6_gal2/1200/800',
    ],
  },
];
